name: Build, Upload Artifacts and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Build Windows
        id: build_windows
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: windows.zip
          preset: windows
          debugMode: "true"
      
      - name: Build Linux
        id: build_linux
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: linux.zip
          preset: linux
          debugMode: "true"
      
      - name: Build Mac
        id: build_mac
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: mac.zip
          preset: mac
          debugMode: "true"
          
      - name: Upload Artifact - Windows
        uses: actions/upload-artifact@v2
        with:
          name: Build artifact - Windows
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}windows.zip

      - name: Upload Artifact - Linux
        uses: actions/upload-artifact@v2
        with:
          name: Build artifact - Linux
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}linux.zip

      - name: Upload Artifact - Mac
        uses: actions/upload-artifact@v2
        with:
          name: Build artifact - Mac
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}mac.zip
                
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/${{ steps.build.outputs.build }}*
