name: Build, Upload Artifacts and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-upload-artifacts-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        platform:
          - name: windows
            file: game.exe
          - name: mac
            file: game.zip
          - name: linux
            file: game.zip
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.5.0
        with:
          name: ${{ matrix.platform.file }}
          preset: ${{ matrix.platform.name }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build artifact - ${{ matrix.platform.name }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Build artifact *"
    
